Greenstand/treetracker-wallet-app

- .prettierrc
- package-lock.json
- package.json
- yarn.lock
The purpose of this PR is to fix #18
> ISSUE #18 Install prettier

- .husky/pre-commit
- .huskyrc
- package.json
The purpose of this PR is to fix #48
> chore: ISSUE #48 Force code format with prettier when commit

- README.md
- package.json
The purpose of this PR is to fix #71
> fix: Issue #71 fix eslint typos in readme

- README.md
The purpose of this PR is to fix #68.
First draft, check for details at #68
> chore: ISSUE #68 Readme about husky/eslint/prettier

- src/App.js
- src/components/PlanterPage.js
- src/components/TokenCard.js
- src/components/TreePage.js
> feat: route: root/wallet/tree/planter

- src/App.js
- src/components/WalletInfo.js
- src/components/common/theme.js
The purpose of this PR is to fix #34 
Reformatted the WalletInfo component to use the colors and to test it.
> chore: ISSUE #34 MatierialUI template/theme

- .eslintrc.js
- package-lock.json
- package.json
- src/components/common/CustomizedTabs.cy.js
- yarn.lock
The purpose of this PR is to fix #50 
Left a test case (commented out) in the 'src/components/common/CustomizedTabs.cy.js' file, so you can test it.
```js
// Test case for eslint
it('waits for a second', () => {
cy.wait(1000)
})
```
Which throws the following error:
> chore: ISSUE #50 Solve the eslint for cypress

- .husky/commit-msg
- README.md
- commitlint.config.js
- package-lock.json
- package.json
- yarn.lock
The purpose of this PR is to fix #103 
Also updated the readme file accordingly.
> chore: issue #103 Add commit rule for project

- src/components/MapDrawer.js
The purpose of this PR is to fix #65 
Added the fade transition to the bottom component, let me know if this is what you were thinking of @dadiorchen
> fix: issue #65 Make drawer smoother

- src/components/MapDrawer.js
The purpose of this PR is to fix #110
> fix: wrong logo position

- package-lock.json
- src/components/MapDrawer.js
- src/components/TokenCard.js
- src/components/TokensArray.js
- src/components/TokensList.js
Fixes #27
this add infinite tokens pagination
> Add TokensList Component [ infinite pagination ]

- src/components/TreePage.js
The purpose of this PR is to fix #119
> fix: issue #119 Add backdrop on the map

- README.md
The purpose of this PR is to fix #109
> chore: issue #109 import openAPI yaml into Postman and Swagger

- src/components/Share.js
- src/components/TreePage.js
- src/components/WalletInfo.js
The purpose of this PR is to fix #76 
Added the share functionality to the tree page.
Also fixed Share function to show the current url.
Added shareUrl prop to the Share function in the Walletinfo component.
> feat: issue #76 share single tree function

- src/components/OptimizedImage.js
- src/components/TokenCard.js
The purpose of this PR is to fix #124
> feat: issue #124 image thumbnail

- src/components/TreePage.js
- src/components/common/DetailPage.js
The purpose of this PR is to fix #151
> fix: issue #151 back button not working

- src/components/Caution.js
The purpose of this PR is to fix #176
> fix: issue #176 MUI error when opening Caution component

- src/components/GroupListCard.cy.js
- src/components/GroupListCard.js
resolves #96 
To create the responsive square grid, I had to make use of a trick. I'm attaching the article here for future reference that explains the trick in-depth.
https://spin.atomicobject.com/2015/07/14/css-responsive-square/
> feat: added group list card component

- src/components/MapDrawer.js
- src/components/Share.js
- src/components/TokenCard.js
- src/components/TokensList.js
- src/components/WalletInfo.js
- src/components/common/CustomizedTabs.js
The purpose of this PR is to fix #163
> style: refine css of wallet page

- src/components/MapDrawer.js
- src/components/MapPage.js
- yarn.lock
The purpose of this PR is to fix #166
> fix: issue #166 The mapdrawer overlap the tree panel

- src/components/TreePage.js
The purpose of this PR is to fix #178
> fix: issue #178 HTML structure issue at history tab

- src/components/TreePage.js
The purpose of this PR is to fix #167
> style: fix distorted tree image

- src/components/TransactionsHistory.js
The purpose of this PR is to fix #172
> fix: issue #172 The last timeline item should not have a link line

- src/components/TreePage.js
- src/components/utils.js
The purpose of this PR is to fix #182
> fix: issue #182 Optimize images on tree page

- src/components/DesktopPage.js
- src/components/MapPage.js
`npm run build` is working now
> fix: build failing

- src/App.js
- src/components/DesktopPage.js
- src/components/Home.js
- src/components/MapDrawer.js
- src/components/MapPage.js
- src/components/TokenGraph.js
- src/components/TokensList.js
- src/components/TransactionsHistory.js
- src/components/TreePage.js
- src/components/WalletInfo.js
- src/components/common/BackButton.js
- src/components/common/DetailPage.js
The purpose of this PR is to fix #193
> fix: issue #193 remove unused variables

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/pull_request_template.md
The following changes have been added :
- bug repost 
- pull request template
Resolved #209
> Issue template

- apps/web/next.config.mjs
Add the correct package name
resolves #227
> chore: add the correct package name

- README.md
> docs: improve README with new sections

- apps/web/README.md
> docs: update readme web

- apps/native/README.md
> docs: update readme native

- .github/pull_request_template.md
Improve pull request template for clarity
> docs: improve pull request template for clarity

- apps/web/src/components/copyright.cy.tsx
There is a import error in the copyright.cy.tsx file that will cause `yarn build` command to fail.
or  
---
---
---
---
---
---
*(Optional) Add any additional comments or notes for reviewers here.*
> fix: correct a typo in copyright.cy.tsx

- apps/web/src/app/login/page.tsx
- apps/web/src/app/signup/page.tsx
- apps/web/src/components/common/CustomSubmitButton.tsx
- apps/web/src/components/common/SocialButtons.tsx
- apps/web/src/components/common/TermsSection.tsx
- apps/web/src/theme.ts
- eslint.config.js
- Updated the theme.ts file to include colours and style in figma mockups
- Removed manually defined colours and styles from components
- Implemented styles created in theme.ts
**Resolves**: #260
---
---
---
---
---
*(Optional) Add any additional comments or notes for reviewers here.*
> feat: moved colours and styling to the mui theme and overrides

- packages/queue/README.md
- packages/queue/__tests__/index.spec.js
- packages/queue/ack.js
- packages/queue/index.js
- packages/queue/package-lock.json
- packages/queue/package.json
- packages/queue/pgClient.js
- packages/queue/publish.js
- packages/queue/subscribe.js
> feat: add postgres messages queue system

- yarn.lock
fix github actions error 
resolves #285
> chore: fix github actions error

- apps/user/README.md
- apps/user/int-tests.config.ts
- apps/user/package.json
- apps/user/src/app.module.ts
- apps/user/src/user/user.controller.spec.int.ts
- apps/user/src/user/user.service.ts
Created integration tests for register endpoint
**Resolves**: #287 
---
---
---
---
---
---
*(Optional) Add any additional comments or notes for reviewers here.*
> fix: user-api integration tests (#287)

- .github/workflows/api-pr.yml
- .github/workflows/build-dev-docker-img-and-relase.yml
- apps/user/.dockerignore
- apps/user/Dockerfile
- apps/user/deployment/base/cluster-role-binding.yaml
- apps/user/deployment/base/cluster-role.yaml
- apps/user/deployment/base/deployment.yaml
- apps/user/deployment/base/kustomization.yaml
- apps/user/deployment/base/mapping.yaml
- apps/user/deployment/base/namespace.yaml
- apps/user/deployment/base/service.yaml
- apps/user/deployment/overlays/development/kustomization.yaml
- apps/user/deployment/overlays/development/mapping.yaml
- apps/user/src/user/user.controller.ts
-[x] `User`
*lint isnt working u guys need to check that out* [https://github.com/Greenstand/treetracker-wallet-app/actions/runs/12340152647/job/34437244103#step:6:32]
> feat: add k8s files and ci cd files for user api

- .github/workflows/api-pr.yml
- .github/workflows/build-dev-docker-img-and-relase.yml
Rename the workspace name in the workspace for the user app.
or  
**Resolves**: #312 
---
---
---
---
---
---
> chore: rename  workspace name

- apps/user/src/app.module.ts
This pull request loads environment secrets into the application user.
**Fixes**:   
or  
**Resolves**:#307 
---
---
---
---
---
---
> chore: load environment secrets

- apps/user/README.md
> Spec: user api access wallet api

- .github/workflows/lint-format.yml
resolves: #370 
---
changes):
the changes):
---
---
---
---
---
> chore: add Prettier check to CI workflow

- .github/pull_request_template.md
> chore: update titles and fix comment in PR template

- packages/queue/__tests__/index.spec.js
- packages/queue/subscribe.js
> fix: update subscribe function with event emitter

- apps/native/app/(auth)/login.tsx
- apps/native/app/(tabs)/home.tsx
- apps/native/app/index.tsx
- apps/native/components/ui/BalanceCard.tsx
- apps/native/components/ui/common/CustomSubmitButton.tsx
- apps/native/utils/dimensions.ts
resolves #359 #358 
---
changes):
the changes):
---
---
---
---
---
> feat: create balance card

- apps/web/cypress/component/ActivityItem.cy.tsx
- apps/web/cypress/component/HomeContent.cy.tsx
- apps/web/cypress/component/RecentActivity.cy.tsx
- apps/web/cypress/component/TokenBalance.cy.tsx
- apps/web/cypress/component/WalletBalance.cy.tsx
- apps/web/src/app/home/ActivityItem.tsx
- apps/web/src/app/home/ActivityList.tsx
- apps/web/src/app/home/RecentActivity.tsx
- apps/web/src/app/home/TokenBalance.tsx
- apps/web/src/app/home/WalletBalance.tsx
- apps/web/src/app/home/page.tsx
- apps/web/src/app/page.tsx
- apps/web/src/components/common/CustomBalanceCard.tsx
##
This PR implements the home page UI based on the provided Figma design for the Wallet Management System.
**Fixes**: #303 
or  
---
the changes):
---
---
| <img width="219" alt="Screenshot 2025-02-23 at 5 26 57 PM" src="https://github.com/user-attachments/assets/32e6a48d-2fef-4b1f-8813-80dde0c934dc" />|<img width="218" alt="Screenshot 2025-02-23 at 5 21 49 PM" src="https://github.com/user-attachments/assets/f196f460-2bed-4dca-812c-b8ca9b77ddc9" />|
---
---
---
> feat: implement home page UI components

- packages/core/package.json
- packages/core/src/api/wallet.ts
- packages/core/src/hooks/index.ts
- packages/core/src/hooks/wallet.ts
- packages/core/src/types/wallet.ts
- yarn.lock
resolves #380 
---
changes):
the changes):
---
---
---
---
---
> feat: add recent activity items

- apps/web/cypress/component/NotificationItem.cy.tsx
- apps/web/cypress/component/NotificationsList.cy.tsx
- apps/web/src/app/notifications/NotificationItem.tsx
- apps/web/src/app/notifications/NotificationsList.tsx
- apps/web/src/app/notifications/page.tsx
- apps/web/src/components/header/Header.tsx
- apps/web/src/components/header/NotificationHeader.tsx
- apps/web/src/components/navigation/BottomNavigatorBar.tsx
Implemented the Notifications Header Page as per the Figma design and added Cypress component tests for the NotificationHeader component.
**Fixes**: #379 
or  
---
changes):
the changes):
---
---
| N/A |<img width="223" alt="Screenshot 2025-03-09 at 5 37 33 AM" src="https://github.com/user-attachments/assets/eb47da92-d47c-4a85-80f2-b7b78f6d5648" />|
---
---
---
> feat: implemented notifications header page

- apps/native/app/(auth)/forgotPassword.tsx
- apps/native/app/(auth)/login.tsx
or  
**Resolves**: #378
---
changes):
the changes):
---
---
---
---
---
> feat: create forgot password screen

- apps/web/src/components/navigation/BottomNavigatorBar.tsx
- apps/web/src/components/navigation/ChooseAction.tsx
or  
resolves: #333 
---
changes):
the changes):
---
---
---
---
---
> feat: implement choose action component

- apps/native/app/(auth)/checkEmail.tsx
or  
**Resolves**: #356 
---
changes):
the changes):
---
---
---
---
---
> feat: check email screen

- apps/web/src/components/navigation/BottomNavigatorBar.tsx
add wallet icon to bottom navigator bar
**Fixes**: #398 
or  
---
changes):
the changes):
---
---
---
---
---
> feat: add wallet icon to bottom navigator bar

- apps/web/src/app/layout.tsx
- apps/web/src/components/ProtectedRoutes.tsx
-  Protect the routes 
**Fixes**: #221   
or  
---
changes):
the changes):
---
> feat: add protected route component

- apps/web/src/components/ProtectedRoutes.tsx
> feat: add temporary localStorage-based auth persistence to ProtectedRoutes

- apps/web/src/app/(auth)/login/page.tsx
> feat: add dynamic login via API and rename email to username

- apps/native/app.config.js
- apps/native/app.json
- apps/native/babel.config.js
- Enable react compiler 
- Activate transformImportMeta
resolves #432
> chore: enable react compiler

- apps/web/cypress/component/WalletItem.cy.tsx
- apps/web/cypress/component/WalletPage.cy.tsx
- apps/web/src/app/wallet/WalletItem.tsx
- apps/web/src/app/wallet/page.tsx
This pull request implements the wallet page for the Wallet Management System as per the Figma design (node-id=377-10307). The feature includes a wallet list view, a drawer for creating new wallets with form validation, a discard confirmation modal, and individual wallet item rendering. State management is added to dynamically update the wallet list, and Cypress component tests ensure functionality.
resolves #391 
---
changes):
the changes):
---
---
|<img width="224" alt="Screenshot 2025-04-06 at 4 30 29 PM" src="https://github.com/user-attachments/assets/4e302632-6c91-43ff-8e9e-b0fc0cf70204" />|<img width="229" alt="Screenshot 2025-04-06 at 4 29 17 PM" …
> feat: implemented wallet page

- apps/native/app/(tabs)/home/index.tsx
- apps/native/components/ui/common/CustomTitle.tsx
- apps/native/constants/Colors.ts
- enhance customTitle 
- add new color
resolves #443
> feat: enhance CustomTitle with style overrides

- apps/native/index.js
- apps/native/index.ts
- Configuration  expo router entry point for monorepo
resolves #445
> feat: configure expo router entry point in monorepo

- apps/user/nest-cli.json
- Add entry file in nest cli config 
resolves #460
> chore: add entry file in nest cli config

- apps/user/nest-cli.json
Reverts Greenstand/treetracker-wallet-app#461
> Revert "chore: add entry file in nest cli config"

- apps/web/src/app/(protected)/send/page.tsx
- apps/web/src/theme.ts
> fix: incorrect MUI variant overrides and types

- apps/native/babel.config.js
- apps/native/package.json
pin react-native reanimated@3.8.0 for Expo 53.0.9 and add the reat
> chore: pin react-native reanimated@3.8.0 for Expo 53

- packages/core/src/utils/storage.ts
> fix: cross-platform storage

- apps/native/app/(auth)/login.tsx
- apps/native/components/ui/common/SocialLoginButton.tsx
Added all the missing buttons/components on login screen. Redirecting to signup link is added.
Formatting and styling rectified according to figma
Finalized the login screen UI and UX to match the Figma design. All missing components such as social login buttons, “Forgot password”, and “Sign up” redirect have been implemented. Styles have been aligned with the design system using the centralized Colors.ts theme.
**Resolves**: #324
---
changes):
the changes):
---
---
Before:
After:
---
---
> feat(login): added missing buttons/components to screen

- apps/web/src/app/(protected)/wallet/page.tsx
- apps/web/src/components/GenericDrawer.tsx
Create info button and drawer UI described in [issue 343](https://github.com/Greenstand/treetracker-wallet-app/issues/343).
**Resolves**: #343
---
changes):
the changes):
---
---
https://github.com/user-attachments/assets/157cfac1-b5ae-47f4-8356-9f7e729f9b4f
---
---
---
The tests are already failing on main branch, but there are no new errors generated in this branch.
> feat: create wallet info tooltip modal

- apps/web/src/app/(public)/forgotPassword/verify/VerifyEmail.tsx
- apps/web/src/app/(public)/forgotPassword/verify/page.tsx
- packages/core/src/api/wallet.ts
- packages/core/src/utils/config.ts
- packages/core/src/utils/validation.ts
or  
---
changes):
the changes):
---
---
---
---
---
> fix: type errors, config cleanup, and Next.js prerender handling

- apps/web/src/app/(protected)/wallet/page.tsx
- apps/web/src/components/WalletCreateDrawer.tsx
**Fixes**: #346 
or  
---
changes):
the changes):
---
---
| "screenshot before" | "<img width="723" height="759" alt="Screen Shot 2025-08-15 at 11 23 15 AM" src="https://github.com/user-attachments/assets/9a9d965f-6519-42fa-bf7d-b94d874337a4" />" |
---
---
---
> feat: add the new wallet empty form with CustomTextField component

- apps/web/.gitignore
- apps/web/cypress.config.ts
- apps/web/cypress/e2e/search-action.cy.ts
- apps/web/cypress/support/commands.ts
- apps/web/cypress/tsconfig.json
- apps/web/src/app/(protected)/home/page.tsx
- apps/web/src/app/(protected)/layout.tsx
- apps/web/src/app/(protected)/search/page.tsx
- apps/web/src/components/ActivityItem.tsx
- apps/web/src/components/GenericModal.tsx
- apps/web/src/components/QRCodeDisplay.tsx
- apps/web/src/components/TransactionSnackbar.tsx
- apps/web/src/components/WalletDetailModal.tsx
- apps/web/src/components/header/Header.tsx
- apps/web/src/components/header/HeaderSearch.tsx
- apps/web/src/components/navigation/BottomNavigatorBar.tsx
- apps/web/src/components/navigation/ChooseAction.tsx
- apps/web/src/context/HeaderContext.tsx
- apps/web/src/context/SnackbarContext.tsx
- Implement search action E2E tests for send and request flows
- Add test selectors and improve Cypress config for environment flexibility
- Add context providers for header and snackbar state management
- Implement TransactionSnackbar and QRCodeDisplay components
- Enhance protected layout with Snackbar and Header providers
- Improve search page with action config, modal, and wallet selection logic
resolves #334 #336 #339 #338
> feat(web): add send/request search actions and UI improvements

- .github/pull_request_template.md
fixes the Pull Request template so that GitHub can correctly recognize issue-closing keywords.
Previously, the template included **Fixes**: # (issue number), which caused GitHub to ignore the keyword.
I updated it to the correct format Fixes #<issue-number> / Resolves #<issue-number> without extra Markdown symbols.
With this change, when contributors open a PR and reference an issue using the template, merging the PR will properly auto-close the linked issue as expected.
**Fixes**: #540   
or  
---
changes):
the changes):
---
---
---
---
---
_(Optional) Add any additional comments or …
> fix: fix pull request template to resolve auto-close issue

- .github/workflows/e2etests.yml
Fixes: # (issue number)  
or  
Resolves: # (issue number)
---
changes):
the changes):
---
---
---
---
---
> fix: useless action
